"""
models/base.py — Abstract base model for all ORM entities.

Every table in the system inherits from BaseModel, which provides:
- UUID primary key (generated by Python, not the database)
- Automatic created_at / updated_at timestamps
- Soft-delete via deleted_at (never hard-delete business data)
- to_dict() base serialization method
"""
import uuid
from datetime import datetime, timezone

from sqlalchemy import Column, DateTime
from sqlalchemy.dialects.postgresql import UUID

from app.extensions import db


class BaseModel(db.Model):
    """Abstract base class. Not mapped to any table."""
    __abstract__ = True

    # ─── Primary key ─────────────────────────────────────────────────────────
    id = Column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        nullable=False,
    )

    # ─── Timestamps ───────────────────────────────────────────────────────────
    created_at = Column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )
    updated_at = Column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )

    # ─── Soft delete ─────────────────────────────────────────────────────────
    deleted_at = Column(DateTime(timezone=True), nullable=True)

    # ─── Methods ─────────────────────────────────────────────────────────────

    def soft_delete(self) -> None:
        """Mark this record as deleted. Does NOT call db.session.commit()."""
        self.deleted_at = datetime.now(timezone.utc)

    def restore(self) -> None:
        """Undo a soft delete."""
        self.deleted_at = None

    @property
    def is_deleted(self) -> bool:
        """True if this record has been soft-deleted."""
        return self.deleted_at is not None

    def to_dict(self) -> dict:
        """
        Base serialization. Subclasses should call super().to_dict()
        and then update the returned dict with their own fields.
        """
        return {
            'id':         str(self.id),
            'created_at': self.created_at.isoformat() if self.created_at else None,
            'updated_at': self.updated_at.isoformat() if self.updated_at else None,
        }

    def __repr__(self) -> str:
        return f'<{self.__class__.__name__} id={self.id}>'
