"""add request and response json to ai_logs

Revision ID: 88d89a7bbcd1
Revises: 77cdd994f796
Create Date: 2026-06-29 14:26:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '88d89a7bbcd1'
down_revision = '77cdd994f796'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('response_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_logs', schema=None) as batch_op:
        batch_op.drop_column('response_json')
        batch_op.drop_column('request_json')
    # ### end Alembic commands ###
